const ACTIONS = {
    LOGIN: 'LOGIN',
    GET_TOKEN: 'GET_TOKEN',
    GET_USER: 'GET_USER',
    GET_ALL_USERS: 'GET_ALL_USERS',
    GET_ALL_PROJECTS:'GET_ALL_PROJECTS',
    DELETE_ONE_PROJECT:'DELETE_ONE_PROJECT',
    UPDATE_ONE_PROJECT:'UPDATE_ONE_PROJECT',
    FETCH_USERS_ALL_PROJECTS:'FETCH_USERS_ALL_PROJECTS'
}

export default ACTIONS